# Project: KBC
# Makefile for Dev-C++ / MinGW

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe

OBJ      = Auth.o GameEngine.o Lifeline.o Player.o Question.o QuestionBank.o Scoreboard.o main.o
LINKOBJ  = Auth.o GameEngine.o Lifeline.o Player.o Question.o QuestionBank.o Scoreboard.o main.o

LIBS     = -static-libgcc
INCS     =
CXXINCS  =
CXXFLAGS = -std=c++98 -Wall -Wextra
CFLAGS   = -std=c98 -Wall -Wextra
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

all-before:

all-after:

BIN = KBC.exe

$(BIN): $(LINKOBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

%.o: %.cpp
	$(CPP) $(CXXFLAGS) $(CXXINCS) -c $< -o $@

clean: clean-custom
	$(RM) $(OBJ) $(BIN)

clean-custom:
